if(EXISTS "/home/runner/work/m/m/build-test/src/libraries/googletest/test/test_googletest[1]_tests.cmake")
  include("/home/runner/work/m/m/build-test/src/libraries/googletest/test/test_googletest[1]_tests.cmake")
else()
  add_test(test_googletest_NOT_BUILT test_googletest_NOT_BUILT)
endif()
