[workspace]
resolver = "2"
members = ["crates/windows-platform-isolation",
  "crates/windows-platform-isolation-sys",
  "crates/windows-threadpool",
  "crates/windows-threadpool-executor",
  "crates/windows-text",
  "crates/windows-text-sys",
  "crates/windows-win32-shim",
  "crates/wordy",
  "crates/talky",
  "crates/squeaky",
]
exclude = ["m"]

[workspace.package]
edition = "2024"
rust-version = "1.96"

[workspace.metadata.spellcheck]
config = "spellcheck.toml"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(fuzzing)',
  'cfg(loom)',
  'cfg(mio_unsupported_force_poll_poll)',
  'cfg(tokio_allow_from_blocking_fd)',
  'cfg(tokio_internal_mt_counters)',
  'cfg(tokio_no_parking_lot)',
  'cfg(tokio_no_tuning_tests)',
  'cfg(tokio_taskdump)',
  'cfg(tokio_unstable)',
  'cfg(tokio_uring)',
  'cfg(target_os, values("cygwin"))',
] }
