if(EXISTS "/home/runner/work/m/m/build-test/src/include/m/utility/test/test_utility[1]_tests.cmake")
  include("/home/runner/work/m/m/build-test/src/include/m/utility/test/test_utility[1]_tests.cmake")
else()
  add_test(test_utility_NOT_BUILT test_utility_NOT_BUILT)
endif()
