if(EXISTS "/home/runner/work/m/m/build-test/src/libraries/error_handling/test/test_error_handling[1]_tests.cmake")
  include("/home/runner/work/m/m/build-test/src/libraries/error_handling/test/test_error_handling[1]_tests.cmake")
else()
  add_test(test_error_handling_NOT_BUILT test_error_handling_NOT_BUILT)
endif()
