// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//
// Dusty-deck legacy open / create integration tests (M-FS-LEGACY-1). The
// executable links m_mwin32 and drives the ANSI 16-bit-era primitives
// mOpenFile / _lopen / _lcreat directly. Its .pilcfg sidecar (generated by
// CMakeLists.txt) enables buffer_updates and a single filesystem redirection,
// so every call runs through the buffered + redirecting provider chain
// in-process: nothing touches the live disk, and the redirection proves the
// OFSTRUCT path the caller reads back is its own public path, never the
// private backing path the redirector maps to (D11 private->public).
//
// The legacy primitives mint their HFILE from the same handle_table as
// mCreateFile, so the minted value is released with mCloseHandle (the legacy
// _lclose lights up later, with M-FS-LEGACY-3 / M-FS-CONTENT).
//

#include <cstdint>
#include <string>

#include <gtest/gtest.h>

#include <m/mwin32/mwinfile.h>

namespace
{
    //
    // The public prefix the redirector maps to a private prefix (see the pilcfg
    // generated in CMakeLists.txt). Files created here are captured by the
    // buffered overlay under the private prefix and never touch the live disk;
    // the leading "C:" anchors a drive root that exists on the host so the
    // overlay can open it.
    //
    constexpr char k_public_root[] = "C:\\mwin32_legacy_pub";

    //
    // Reconstruct the minted HANDLE from an HFILE so the legacy handle can be
    // released through mCloseHandle. The minted value fits in a positive 31-bit
    // int (reserved encoding: bit 30 set, nothing at or above bit 31), so the
    // round-trip through uintptr_t is lossless.
    //
    HANDLE
    hfile_to_handle(HFILE hf)
    {
        return reinterpret_cast<HANDLE>(static_cast<std::uintptr_t>(hf));
    }

    void
    close_hfile(HFILE hf)
    {
        EXPECT_TRUE(::mCloseHandle(hfile_to_handle(hf)));
    }
} // namespace

TEST(MwinFileLegacy, OpenFileCreatesAndReopens)
{
    std::string const dir  = std::string(k_public_root) + "\\create";
    std::string const file = dir + "\\data.bin";

    ::mCreateDirectoryA(dir.c_str(), nullptr);

    // OF_CREATE truncates / creates and hands back a live HFILE.
    OFSTRUCT ofs{};
    HFILE const hc = ::mOpenFile(file.c_str(), &ofs, OF_CREATE | OF_READWRITE);
    ASSERT_NE(hc, HFILE_ERROR);
    EXPECT_STREQ(ofs.szPathName, file.c_str());
    close_hfile(hc);

    // Reopening the same file for read succeeds and yields a distinct live
    // handle. The OFSTRUCT again carries the caller's public path.
    OFSTRUCT reopen{};
    HFILE const ho = ::mOpenFile(file.c_str(), &reopen, OF_READ);
    ASSERT_NE(ho, HFILE_ERROR);
    EXPECT_STREQ(reopen.szPathName, file.c_str());
    close_hfile(ho);
}

TEST(MwinFileLegacy, LCreatThenLOpen)
{
    std::string const dir  = std::string(k_public_root) + "\\lcreat";
    std::string const file = dir + "\\data.bin";

    ::mCreateDirectoryA(dir.c_str(), nullptr);

    HFILE const hc = ::m_lcreat(file.c_str(), 0);
    ASSERT_NE(hc, HFILE_ERROR);
    close_hfile(hc);

    HFILE const ho = ::m_lopen(file.c_str(), OF_READWRITE);
    ASSERT_NE(ho, HFILE_ERROR);
    close_hfile(ho);
}

TEST(MwinFileLegacy, ExistProbeReportsPresence)
{
    std::string const dir     = std::string(k_public_root) + "\\exist";
    std::string const present = dir + "\\there.bin";
    std::string const missing = dir + "\\gone.bin";

    ::mCreateDirectoryA(dir.c_str(), nullptr);

    HFILE const hc = ::m_lcreat(present.c_str(), 0);
    ASSERT_NE(hc, HFILE_ERROR);
    close_hfile(hc);

    // OF_EXIST opens then immediately releases the handle, reporting a non-error
    // result for a file that is present and HFILE_ERROR for one that is not. The
    // success value carries no live table entry, so it must not be closed.
    OFSTRUCT ofs{};
    EXPECT_NE(::mOpenFile(present.c_str(), &ofs, OF_EXIST), HFILE_ERROR);
    EXPECT_EQ(::mOpenFile(missing.c_str(), &ofs, OF_EXIST), HFILE_ERROR);
}

TEST(MwinFileLegacy, OpenMissingFileFails)
{
    std::string const dir     = std::string(k_public_root) + "\\missing";
    std::string const missing = dir + "\\nope.bin";

    ::mCreateDirectoryA(dir.c_str(), nullptr);

    EXPECT_EQ(::m_lopen(missing.c_str(), OF_READ), HFILE_ERROR);
    EXPECT_EQ(::mOpenFile(missing.c_str(), nullptr, OF_READ), HFILE_ERROR);
}
