// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//
// Path-based copy / replace / temp-file / path-resolution integration tests
// (M-FS-COPY-5). The executable links m_mwin32 and calls the m-prefixed
// filesystem entry points directly. Its .pilcfg sidecar (generated by CMake)
// enables buffer_updates and a single filesystem redirection, so every call
// runs through the buffered + redirecting provider chain in-process: nothing
// touches the live disk. The redirection also proves the path-resolution family
// hands back the caller's public path, never the private path the redirector
// maps to (D11 private->public).
//
// Scope reminder (D14): copies are namespace-only (the destination node is
// created empty; byte content is deferred to M-FS-CONTENT) and metadata writes
// are accepted no-ops, so these tests assert node existence and namespace
// re-keying, never byte content.
//

#include <gtest/gtest.h>

#include <string>

#include <m/mwin32/mwinfile.h>

namespace
{
    //
    // The public prefix the redirector maps to a private prefix (see the pilcfg
    // generated in CMakeLists.txt). Nodes created here are captured by the
    // buffered overlay under the private prefix and never touch the live disk;
    // the leading "C:" anchors a drive root that exists on the host so the
    // overlay can open it.
    //
    constexpr wchar_t k_public_root[] = L"C:\\mwin32_copy_pub";

    //
    // Create a directory and a fresh, zero-length file inside it through the
    // shim. Returns true when both succeed.
    //
    bool
    make_file(std::wstring const& dir, std::wstring const& file)
    {
        ::mCreateDirectoryW(dir.c_str(), nullptr);

        HANDLE const h = ::mCreateFileW(file.c_str(),
                                        GENERIC_WRITE,
                                        0,
                                        nullptr,
                                        CREATE_ALWAYS,
                                        FILE_ATTRIBUTE_NORMAL,
                                        nullptr);
        if (h == INVALID_HANDLE_VALUE)
            return false;

        ::mCloseHandle(h);
        return true;
    }

    //
    // True when a node exists at the given path (by-path attribute query
    // succeeds).
    //
    bool
    node_exists(std::wstring const& path)
    {
        WIN32_FILE_ATTRIBUTE_DATA data{};
        return ::mGetFileAttributesExW(path.c_str(), GetFileExInfoStandard, &data) != FALSE;
    }
} // namespace

TEST(MwinFileCopy, CopyFileCreatesDestinationNode)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\copy";
    std::wstring const src = dir + L"\\src.bin";
    std::wstring const dst = dir + L"\\dst.bin";

    ASSERT_TRUE(make_file(dir, src));

    EXPECT_TRUE(::mCopyFileW(src.c_str(), dst.c_str(), FALSE));
    EXPECT_TRUE(node_exists(dst));
}

TEST(MwinFileCopy, CopyFileFailsWhenDestinationExistsAndFlagSet)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\copyfail";
    std::wstring const src = dir + L"\\src.bin";
    std::wstring const dst = dir + L"\\dst.bin";

    ASSERT_TRUE(make_file(dir, src));
    ASSERT_TRUE(make_file(dir, dst));

    // bFailIfExists = TRUE: the existing destination must block the copy.
    EXPECT_FALSE(::mCopyFileW(src.c_str(), dst.c_str(), TRUE));
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_FILE_EXISTS));
}

TEST(MwinFileCopy, CopyFileFailsWhenSourceMissing)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\copymissing";
    std::wstring const src = dir + L"\\nope.bin";
    std::wstring const dst = dir + L"\\dst.bin";

    ::mCreateDirectoryW(dir.c_str(), nullptr);

    EXPECT_FALSE(::mCopyFileW(src.c_str(), dst.c_str(), FALSE));
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_FILE_NOT_FOUND));
}

TEST(MwinFileCopy, CopyFileExHonoursFailIfExistsFlag)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\copyex";
    std::wstring const src = dir + L"\\src.bin";
    std::wstring const dst = dir + L"\\dst.bin";

    ASSERT_TRUE(make_file(dir, src));

    // First copy with the fail-if-exists flag succeeds (destination absent).
    EXPECT_TRUE(::mCopyFileExW(src.c_str(), dst.c_str(), nullptr, nullptr, nullptr, COPY_FILE_FAIL_IF_EXISTS));
    EXPECT_TRUE(node_exists(dst));

    // Second copy with the same flag fails (destination now present).
    EXPECT_FALSE(::mCopyFileExW(src.c_str(), dst.c_str(), nullptr, nullptr, nullptr, COPY_FILE_FAIL_IF_EXISTS));
}

TEST(MwinFileCopy, ReplaceFileReKeysAndBacksUp)
{
    std::wstring const dir         = std::wstring(k_public_root) + L"\\replace";
    std::wstring const replaced    = dir + L"\\target.bin";
    std::wstring const replacement = dir + L"\\incoming.bin";
    std::wstring const backup      = dir + L"\\target.bak";

    ASSERT_TRUE(make_file(dir, replaced));
    ASSERT_TRUE(make_file(dir, replacement));

    EXPECT_TRUE(::mReplaceFileW(replaced.c_str(),
                               replacement.c_str(),
                               backup.c_str(),
                               0,
                               nullptr,
                               nullptr));

    // The replacement node is re-keyed onto the replaced name, the old replaced
    // node is preserved at the backup name, and the replacement name is gone.
    EXPECT_TRUE(node_exists(replaced));
    EXPECT_TRUE(node_exists(backup));
    EXPECT_FALSE(node_exists(replacement));
}

TEST(MwinFileCopy, ReplaceFileWithoutBackupDiscardsReplaced)
{
    std::wstring const dir         = std::wstring(k_public_root) + L"\\replacenobak";
    std::wstring const replaced    = dir + L"\\target.bin";
    std::wstring const replacement = dir + L"\\incoming.bin";

    ASSERT_TRUE(make_file(dir, replaced));
    ASSERT_TRUE(make_file(dir, replacement));

    EXPECT_TRUE(::mReplaceFileW(replaced.c_str(), replacement.c_str(), nullptr, 0, nullptr, nullptr));

    EXPECT_TRUE(node_exists(replaced));
    EXPECT_FALSE(node_exists(replacement));
}

TEST(MwinFileCopy, CreateDirectoryExCreatesDirectory)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\direx";

    EXPECT_TRUE(::mCreateDirectoryExW(nullptr, dir.c_str(), nullptr));
    EXPECT_TRUE(node_exists(dir));
}

TEST(MwinFileCopy, GetTempFileNameMintsAndCreatesUniqueNodes)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\temp";
    ::mCreateDirectoryW(dir.c_str(), nullptr);

    wchar_t   first[MAX_PATH]  = {};
    wchar_t   second[MAX_PATH] = {};
    UINT const u1 = ::mGetTempFileNameW(dir.c_str(), L"tmp", 0, first);
    UINT const u2 = ::mGetTempFileNameW(dir.c_str(), L"tmp", 0, second);

    EXPECT_NE(u1, 0u);
    EXPECT_NE(u2, 0u);
    EXPECT_NE(u1, u2);

    // Both minted names must name freshly created nodes ...
    EXPECT_TRUE(node_exists(first));
    EXPECT_TRUE(node_exists(second));

    // ... and the two names must differ.
    EXPECT_STRNE(first, second);
}

TEST(MwinFileCopy, GetTempFileNameWithExplicitUniqueDoesNotCreate)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\tempexplicit";
    ::mCreateDirectoryW(dir.c_str(), nullptr);

    constexpr UINT k_unique = 0x1234u;

    wchar_t    buffer[MAX_PATH] = {};
    UINT const u = ::mGetTempFileNameW(dir.c_str(), L"tmp", k_unique, buffer);

    EXPECT_EQ(u, k_unique);

    // A non-zero uUnique forms the name but creates no node.
    EXPECT_FALSE(node_exists(buffer));
}

TEST(MwinFileCopy, SetFileAttributesValidatesExistence)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\attrs";
    std::wstring const file = dir + L"\\data.bin";

    ASSERT_TRUE(make_file(dir, file));

    // An existing target succeeds (the attribute mask is an accepted no-op).
    EXPECT_TRUE(::mSetFileAttributesW(file.c_str(), FILE_ATTRIBUTE_READONLY));

    // A missing target fails ERROR_FILE_NOT_FOUND.
    std::wstring const missing = dir + L"\\nope.bin";
    EXPECT_FALSE(::mSetFileAttributesW(missing.c_str(), FILE_ATTRIBUTE_NORMAL));
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_FILE_NOT_FOUND));
}

TEST(MwinFileCopy, GetFullPathNameCanonicalizesAndReportsFilePart)
{
    wchar_t  buffer[MAX_PATH] = {};
    wchar_t* file_part        = nullptr;

    DWORD const n = ::mGetFullPathNameW(L"C:\\a\\.\\b\\..\\c.txt", MAX_PATH, buffer, &file_part);

    ASSERT_GT(n, 0u);
    EXPECT_STREQ(buffer, L"C:\\a\\c.txt");

    // The file part must point at the final component within the caller buffer.
    ASSERT_NE(file_part, nullptr);
    EXPECT_STREQ(file_part, L"c.txt");
    EXPECT_EQ(file_part, buffer + (n - 5));
}

TEST(MwinFileCopy, GetFullPathNameReportsRequiredSizeWhenBufferTooSmall)
{
    wchar_t* file_part = nullptr;

    // A zero-length buffer forces the required-size branch (length including the
    // terminator).
    DWORD const required = ::mGetFullPathNameW(L"C:\\a\\c.txt", 0, nullptr, &file_part);

    EXPECT_EQ(required, static_cast<DWORD>(std::wstring(L"C:\\a\\c.txt").size() + 1));
    EXPECT_EQ(file_part, nullptr);
}

TEST(MwinFileCopy, GetLongPathNameRequiresExistence)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\long";
    std::wstring const file = dir + L"\\data.bin";

    ASSERT_TRUE(make_file(dir, file));

    wchar_t     buffer[MAX_PATH] = {};
    DWORD const n = ::mGetLongPathNameW(file.c_str(), buffer, MAX_PATH);
    ASSERT_GT(n, 0u);
    EXPECT_STREQ(buffer, file.c_str());

    // A path that does not exist fails ERROR_FILE_NOT_FOUND.
    std::wstring const missing = dir + L"\\nope.bin";
    EXPECT_EQ(::mGetLongPathNameW(missing.c_str(), buffer, MAX_PATH), 0u);
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_FILE_NOT_FOUND));
}

TEST(MwinFileCopy, SearchPathFindsExistingFile)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\search";
    std::wstring const file = dir + L"\\found.bin";

    ASSERT_TRUE(make_file(dir, file));

    wchar_t  buffer[MAX_PATH] = {};
    wchar_t* file_part        = nullptr;

    DWORD const n =
        ::mSearchPathW(dir.c_str(), L"found.bin", nullptr, MAX_PATH, buffer, &file_part);

    ASSERT_GT(n, 0u);
    EXPECT_STREQ(buffer, file.c_str());
    ASSERT_NE(file_part, nullptr);
    EXPECT_STREQ(file_part, L"found.bin");
}

TEST(MwinFileCopy, SearchPathAppendsDefaultExtension)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\searchext";
    std::wstring const file = dir + L"\\program.exe";

    ASSERT_TRUE(make_file(dir, file));

    wchar_t  buffer[MAX_PATH] = {};
    wchar_t* file_part        = nullptr;

    // The name carries no extension, so the default ".exe" is appended before
    // the lookup.
    DWORD const n =
        ::mSearchPathW(dir.c_str(), L"program", L".exe", MAX_PATH, buffer, &file_part);

    ASSERT_GT(n, 0u);
    EXPECT_STREQ(buffer, file.c_str());
}

TEST(MwinFileCopy, SearchPathFailsWhenFileMissing)
{
    std::wstring const dir = std::wstring(k_public_root) + L"\\searchmissing";
    ::mCreateDirectoryW(dir.c_str(), nullptr);

    wchar_t  buffer[MAX_PATH] = {};
    wchar_t* file_part        = nullptr;

    EXPECT_EQ(::mSearchPathW(dir.c_str(), L"absent.bin", nullptr, MAX_PATH, buffer, &file_part), 0u);
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_FILE_NOT_FOUND));
}
