// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//
// Handle-based metadata family integration tests (M-FS-HANDLE-META-4). The
// executable links m_mwin32 and calls the m-prefixed filesystem entry points
// directly. Its .pilcfg sidecar (generated by CMake) enables buffer_updates and
// a single filesystem redirection, so every call runs through the buffered +
// redirecting provider chain in-process: a file is created via mCreateFileW
// under the public prefix, its metadata is read back by handle, and the answers
// are checked for consistency against the by-path metadata. The redirection
// also proves mGetFinalPathNameByHandle hands back the caller's public path,
// never the private path the redirector maps to (D11 private->public).
//

#include <gtest/gtest.h>

#include <m/mwin32/mwinfile.h>

namespace
{
    //
    // The public prefix the redirector maps to a private prefix (see the pilcfg
    // generated in CMakeLists.txt). Files created here are captured by the
    // buffered overlay under the private prefix and never touch the live disk;
    // the leading "C:" anchors a drive root that exists on the host so the
    // overlay can open it.
    //
    constexpr wchar_t k_public_root[] = L"C:\\mwin32_meta_pub";

    //
    // A second prefix with no redirection rule. A path here flows through the
    // redirecting layer unchanged (no prefix match) and is served by the
    // buffered overlay, exercising the buffered-only path.
    //
    constexpr wchar_t k_plain_root[] = L"C:\\mwin32_meta_plain";

    //
    // Create a directory and a fresh, zero-length file inside it through the
    // shim, returning the minted handle. The caller owns the handle and must
    // close it with mCloseHandle.
    //
    HANDLE
    create_test_file(std::wstring const& dir, std::wstring const& file)
    {
        ::mCreateDirectoryW(dir.c_str(), nullptr);

        return ::mCreateFileW(file.c_str(),
                              GENERIC_WRITE,
                              0,
                              nullptr,
                              CREATE_ALWAYS,
                              FILE_ATTRIBUTE_NORMAL,
                              nullptr);
    }
} // namespace

TEST(MwinFileHandleMeta, GetFileInformationByHandleServesMetadata)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\info";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    BY_HANDLE_FILE_INFORMATION bhfi{};
    EXPECT_TRUE(::mGetFileInformationByHandle(h, &bhfi));

    // A freshly created file is not a directory, models a single hard link, and
    // (content is out of scope, D14) has zero size.
    EXPECT_EQ(bhfi.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY, 0u);
    EXPECT_EQ(bhfi.nNumberOfLinks, 1u);
    EXPECT_EQ(bhfi.nFileSizeLow, 0u);
    EXPECT_EQ(bhfi.nFileSizeHigh, 0u);

    // The by-handle attributes must agree with the by-path attributes: both are
    // the identical query_information answer routed through the same chain.
    WIN32_FILE_ATTRIBUTE_DATA by_path{};
    ASSERT_TRUE(::mGetFileAttributesExW(file.c_str(), GetFileExInfoStandard, &by_path));
    EXPECT_EQ(bhfi.dwFileAttributes, by_path.dwFileAttributes);

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, GetFileSizeReportsZeroForNewFile)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\size";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    DWORD high = 0xDEAD'BEEFu;
    DWORD const low = ::mGetFileSize(h, &high);
    EXPECT_EQ(low, 0u);
    EXPECT_EQ(high, 0u);

    LARGE_INTEGER size{};
    size.QuadPart = -1;
    EXPECT_TRUE(::mGetFileSizeEx(h, &size));
    EXPECT_EQ(size.QuadPart, 0);

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, GetFileTimeMatchesByHandleInformation)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\time";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    BY_HANDLE_FILE_INFORMATION bhfi{};
    ASSERT_TRUE(::mGetFileInformationByHandle(h, &bhfi));

    FILETIME creation{}, access{}, write{};
    EXPECT_TRUE(::mGetFileTime(h, &creation, &access, &write));

    // mGetFileTime and mGetFileInformationByHandle read the same node metadata,
    // so the timestamps must be bit-identical.
    EXPECT_EQ(creation.dwLowDateTime, bhfi.ftCreationTime.dwLowDateTime);
    EXPECT_EQ(creation.dwHighDateTime, bhfi.ftCreationTime.dwHighDateTime);
    EXPECT_EQ(write.dwLowDateTime, bhfi.ftLastWriteTime.dwLowDateTime);
    EXPECT_EQ(write.dwHighDateTime, bhfi.ftLastWriteTime.dwHighDateTime);

    // The Set* metadata verbs are accepted (no PIL write verb this milestone) and
    // must report success without disturbing the handle.
    EXPECT_TRUE(::mSetFileTime(h, &creation, &access, &write));

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, GetFileTypeIsDiskForMintedHandle)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\type";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    EXPECT_EQ(::mGetFileType(h), static_cast<DWORD>(FILE_TYPE_DISK));

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, FinalPathNameReturnsPublicPath)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\final";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    wchar_t      buffer[MAX_PATH] = {};
    DWORD const  n = ::mGetFinalPathNameByHandleW(h, buffer, MAX_PATH, VOLUME_NAME_DOS);
    ASSERT_GT(n, 0u);
    ASSERT_LT(n, static_cast<DWORD>(MAX_PATH));

    std::wstring const final_path(buffer, n);

    // The redirector maps mwin32_meta_pub -> mwin32_meta_priv internally, but the
    // caller opened a public path and must read the public path back.
    EXPECT_NE(final_path.find(L"mwin32_meta_pub"), std::wstring::npos);
    EXPECT_EQ(final_path.find(L"mwin32_meta_priv"), std::wstring::npos);

    // The default DOS form carries the extended-length escape prefix.
    EXPECT_EQ(final_path.rfind(L"\\\\?\\", 0), 0u);

    // The volume-less form drops the drive and keeps a single leading separator.
    wchar_t     rel_buffer[MAX_PATH] = {};
    DWORD const rel_n =
        ::mGetFinalPathNameByHandleW(h, rel_buffer, MAX_PATH, VOLUME_NAME_NONE);
    ASSERT_GT(rel_n, 0u);
    std::wstring const rel_path(rel_buffer, rel_n);
    EXPECT_EQ(rel_path.rfind(L"\\mwin32_meta_pub", 0), 0u);

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, FinalPathNameShortBufferReportsRequiredSize)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\shortbuf";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    // A zero-length buffer cannot hold the result; the API returns the required
    // size including the null terminator and writes nothing.
    DWORD const required = ::mGetFinalPathNameByHandleW(h, nullptr, 0, VOLUME_NAME_DOS);
    EXPECT_GT(required, 1u);

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, GetInformationByHandleExServesMetadataClasses)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\infoex";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    FILE_BASIC_INFO basic{};
    EXPECT_TRUE(::mGetFileInformationByHandleEx(h, FileBasicInfo, &basic, sizeof(basic)));
    EXPECT_EQ(basic.FileAttributes & FILE_ATTRIBUTE_DIRECTORY, 0u);

    FILE_STANDARD_INFO standard{};
    EXPECT_TRUE(
        ::mGetFileInformationByHandleEx(h, FileStandardInfo, &standard, sizeof(standard)));
    EXPECT_EQ(standard.EndOfFile.QuadPart, 0);
    EXPECT_EQ(standard.Directory, FALSE);

    // FileNameInfo is variable length; a generous buffer holds the volume-relative
    // public path.
    alignas(FILE_NAME_INFO) unsigned char name_storage[sizeof(FILE_NAME_INFO) + MAX_PATH * sizeof(WCHAR)] = {};
    auto* name_info = reinterpret_cast<FILE_NAME_INFO*>(name_storage);
    EXPECT_TRUE(
        ::mGetFileInformationByHandleEx(h, FileNameInfo, name_info, sizeof(name_storage)));
    std::wstring const name(name_info->FileName, name_info->FileNameLength / sizeof(WCHAR));
    EXPECT_NE(name.find(L"mwin32_meta_pub"), std::wstring::npos);

    // A stream / content class is deferred (M-FS-CONTENT).
    FILE_STREAM_INFO stream{};
    EXPECT_FALSE(::mGetFileInformationByHandleEx(h, FileStreamInfo, &stream, sizeof(stream)));
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_NOT_SUPPORTED));

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, SetInformationByHandleAcceptsMetadataDefersContent)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\setinfo";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    // A metadata class is accepted (no-op success).
    FILE_BASIC_INFO basic{};
    ASSERT_TRUE(::mGetFileInformationByHandleEx(h, FileBasicInfo, &basic, sizeof(basic)));
    EXPECT_TRUE(::mSetFileInformationByHandle(h, FileBasicInfo, &basic, sizeof(basic)));

    // An end-of-file resize is byte content and is deferred (M-FS-CONTENT).
    FILE_END_OF_FILE_INFO eof{};
    eof.EndOfFile.QuadPart = 4096;
    EXPECT_FALSE(::mSetFileInformationByHandle(h, FileEndOfFileInfo, &eof, sizeof(eof)));
    EXPECT_EQ(::GetLastError(), static_cast<DWORD>(ERROR_NOT_SUPPORTED));

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, MetadataServedOnBufferedOnlyPath)
{
    // A prefix with no redirection rule exercises the buffered overlay without
    // any path mapping; the by-handle metadata must still be served and the
    // final path must echo the same (unmapped) path back.
    std::wstring const dir  = std::wstring(k_plain_root) + L"\\plain";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    BY_HANDLE_FILE_INFORMATION bhfi{};
    EXPECT_TRUE(::mGetFileInformationByHandle(h, &bhfi));
    EXPECT_EQ(bhfi.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY, 0u);

    wchar_t      buffer[MAX_PATH] = {};
    DWORD const  n = ::mGetFinalPathNameByHandleW(h, buffer, MAX_PATH, VOLUME_NAME_DOS);
    ASSERT_GT(n, 0u);
    std::wstring const final_path(buffer, n);
    EXPECT_NE(final_path.find(L"mwin32_meta_plain"), std::wstring::npos);

    EXPECT_TRUE(::mCloseHandle(h));
}

TEST(MwinFileHandleMeta, GetFileInformationByHandleAnsiFinalPath)
{
    std::wstring const dir  = std::wstring(k_public_root) + L"\\ansi";
    std::wstring const file = dir + L"\\data.bin";

    HANDLE const h = create_test_file(dir, file);
    ASSERT_NE(h, INVALID_HANDLE_VALUE);

    char        buffer[MAX_PATH] = {};
    DWORD const n = ::mGetFinalPathNameByHandleA(h, buffer, MAX_PATH, VOLUME_NAME_DOS);
    ASSERT_GT(n, 0u);
    std::string const final_path(buffer, n);
    EXPECT_NE(final_path.find("mwin32_meta_pub"), std::string::npos);
    EXPECT_EQ(final_path.find("mwin32_meta_priv"), std::string::npos);

    EXPECT_TRUE(::mCloseHandle(h));
}
