if(EXISTS "/home/runner/work/m/m/build-test/src/libraries/const_string/test/test_const_string[1]_tests.cmake")
  include("/home/runner/work/m/m/build-test/src/libraries/const_string/test/test_const_string[1]_tests.cmake")
else()
  add_test(test_const_string_NOT_BUILT test_const_string_NOT_BUILT)
endif()
