if(EXISTS "/home/runner/work/m/m/build-test/src/libraries/math/test/test_math[1]_tests.cmake")
  include("/home/runner/work/m/m/build-test/src/libraries/math/test/test_math[1]_tests.cmake")
else()
  add_test(test_math_NOT_BUILT test_math_NOT_BUILT)
endif()
