// Copyright (c) Microsoft Corporation.

//! `wordy`'s word-domain core — the dictionary business logic.
//!
//! This module is the heart of what `wordy` *does*: it owns an in-memory
//! "shared dictionary" and answers the four questions the service is built
//! around — *is this a word?* (spell-check membership), *which words match this
//! pattern?* (`regex` enumeration), *which words can I build from these tiles?*
//! (the anagram solver), and *what did you mean?* (`fst` edit-distance
//! suggestions).
//!
//! It is deliberately **pure**: no IIS, no filesystem, no isolation awareness
//! (windows-win32-shim SHIM-D19). The only input is the vendored SCOWL `en-US`
//! word list embedded at compile time. Because nothing here touches a host, the
//! whole module is unit-testable on any platform — the no-HWC end-goal in
//! miniature (MW13-2).
//!
//! ## Owned behavioral specification (Design Autonomy)
//!
//! `wordy` *defines* the following behavior; the `fst` and `regex` crates are
//! chosen because they satisfy it, not the other way around:
//!
//! - The shared dictionary is a **case-folded** set of word forms: every entry
//!   from the source list is lowercased on load, and membership / enumeration /
//!   suggestions are therefore case-insensitive.
//! - **Membership** ([`Dictionary::contains`]) is exact (after case folding).
//! - **Enumeration** ([`Dictionary::matching_regex`]) returns every dictionary
//!   word the supplied pattern matches *in full* (the pattern is anchored to the
//!   whole word), in ascending lexicographic order.
//! - The **anagram** solver ([`Dictionary::anagrams`]) is driven by a positional
//!   [`AnagramQuery`]: the template's length fixes the candidate word length,
//!   each [`Slot::Fixed`] position is a free given that must match exactly, and
//!   each [`Slot::Blank`] position must be filled by drawing a letter from the
//!   supplied [`LetterMultiset`]; a deficit of needed letters may be covered by a
//!   bounded number of wildcard tiles, each standing for any one letter.
//! - **Suggestions** ([`Dictionary::suggestions`]) return every dictionary word
//!   within a Levenshtein edit distance of the (case-folded) query, in ascending
//!   lexicographic order.
//!
//! The vendored list is `wordlist/en_US.txt`, generated by the SCOWL / ESDB
//! custom-list tool (US spelling, medium size, diacritics stripped, offensive
//! categories excluded); its license travels beside it in `wordlist/COPYING.SCOWL`.

use std::collections::BTreeSet;
use std::sync::LazyLock;

use fst::automaton::Levenshtein;
use fst::{IntoStreamer, Set, SetBuilder, Streamer};
use regex::Regex;

/// The locales `wordy` can serve. Only [`Locale::EnUs`] is populated today; the
/// enum exists so additional locales drop in without a schema change
/// (windows-win32-shim SHIM-D19, "forward-compatible identity / locale").
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Locale {
    /// US English — backed by the vendored SCOWL `en-US` list.
    EnUs,
}

impl Locale {
    /// A stable, path-safe directory slug for this locale, used to namespace
    /// per-locale storage such as the custom-dictionary FS store.
    pub fn slug(self) -> &'static str {
        match self {
            Locale::EnUs => "en-US",
        }
    }

    /// The compile-time-embedded source word list for this locale, one word per
    /// line. The license for the data lives beside it in `wordlist/COPYING.SCOWL`.
    fn source(self) -> &'static str {
        match self {
            Locale::EnUs => include_str!("../wordlist/en_US.txt"),
        }
    }
}

/// Errors the word-domain core can return.
///
/// These describe *caller-supplied* problems (a malformed pattern, non-letter
/// tray, etc.) and the one internal invariant that could in principle fail
/// (building the dictionary from the vendored list).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WordError {
    /// The supplied enumeration pattern is not a valid regular expression. The
    /// payload is the underlying compiler message.
    InvalidRegex(String),
    /// A tray / letter string contained a character that is not an ASCII letter
    /// (and not ignorable whitespace). The payload is the offending input.
    InvalidLetters(String),
    /// An anagram template contained a character that is neither an ASCII letter
    /// (a fixed given) nor the blank marker `'.'`. The payload is the input.
    InvalidTemplate(String),
    /// The requested suggestion edit distance produced an automaton too large to
    /// build. The payload is the underlying `fst` message.
    SuggestionTooBroad(String),
    /// The vendored dictionary failed to build. The payload is the underlying
    /// `fst` message. This indicates a corrupt vendored list, not bad input.
    DictionaryBuild(String),
}

impl std::fmt::Display for WordError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WordError::InvalidRegex(m) => write!(f, "invalid enumeration pattern: {m}"),
            WordError::InvalidLetters(s) => write!(f, "tray contains non-letter input: {s:?}"),
            WordError::InvalidTemplate(s) => write!(f, "invalid anagram template: {s:?}"),
            WordError::SuggestionTooBroad(m) => write!(f, "suggestion query too broad: {m}"),
            WordError::DictionaryBuild(m) => write!(f, "failed to build dictionary: {m}"),
        }
    }
}

impl std::error::Error for WordError {}

/// A multiset of ASCII letters (`a`–`z`) — the "tray" of tiles available to fill
/// the blanks of an [`AnagramQuery`].
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct LetterMultiset {
    /// Count of each letter, indexed `0 == 'a'` … `25 == 'z'`.
    counts: [u32; 26],
}

impl LetterMultiset {
    /// Build a multiset from a string of letters. ASCII letters are counted
    /// case-insensitively; ASCII whitespace is ignored (so `"a b c"` is allowed);
    /// any other character yields [`WordError::InvalidLetters`].
    pub fn from_letters(letters: &str) -> Result<Self, WordError> {
        let mut counts = [0u32; 26];
        for ch in letters.chars() {
            if let Some(idx) = letter_index(ch.to_ascii_lowercase()) {
                counts[idx] += 1;
            } else if ch.is_whitespace() {
                continue;
            } else {
                return Err(WordError::InvalidLetters(letters.to_string()));
            }
        }
        Ok(LetterMultiset { counts })
    }

    /// The number of available tiles of the given letter (`0` if `letter` is not
    /// an ASCII `a`–`z` character).
    pub fn count(&self, letter: char) -> u32 {
        letter_index(letter.to_ascii_lowercase()).map_or(0, |idx| self.counts[idx])
    }

    /// The total number of tiles in the tray.
    pub fn total(&self) -> u32 {
        self.counts.iter().sum()
    }
}

/// One position of an [`AnagramQuery`] template.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Slot {
    /// A fixed given letter that must appear, as-is, at this position. It is
    /// "free": it does not consume a tile from the tray.
    Fixed(char),
    /// A blank to be filled by drawing one letter from the tray (or, failing
    /// that, a wildcard tile).
    Blank,
}

/// A positional anagram query.
///
/// The `template` fixes the candidate word length and which positions are given
/// versus blank; the `tray` supplies letters for the blanks; `wildcards` are
/// extra tiles that may each stand for any one letter when the tray cannot cover
/// a blank.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnagramQuery {
    /// The positional template; its length is the required word length.
    pub template: Vec<Slot>,
    /// Letters available to fill [`Slot::Blank`] positions.
    pub tray: LetterMultiset,
    /// Number of wildcard tiles available to cover letters the tray lacks.
    pub wildcards: usize,
}

impl AnagramQuery {
    /// Build a query from typed parts.
    pub fn new(template: Vec<Slot>, tray: LetterMultiset, wildcards: usize) -> Self {
        AnagramQuery {
            template,
            tray,
            wildcards,
        }
    }

    /// Parse a query from string forms.
    ///
    /// In `template`, an ASCII letter is a fixed given (case-insensitive) and the
    /// dot `'.'` marks a blank to fill from the tray; any other character yields
    /// [`WordError::InvalidTemplate`]. `tray` is parsed by
    /// [`LetterMultiset::from_letters`]. `wildcards` is the count of any-letter
    /// tiles (passed separately so a tray of real letters is never ambiguous).
    pub fn parse(template: &str, tray: &str, wildcards: usize) -> Result<Self, WordError> {
        let mut slots = Vec::with_capacity(template.len());
        for ch in template.chars() {
            let lc = ch.to_ascii_lowercase();
            if lc == '.' {
                slots.push(Slot::Blank);
            } else if lc.is_ascii_lowercase() {
                slots.push(Slot::Fixed(lc));
            } else {
                return Err(WordError::InvalidTemplate(template.to_string()));
            }
        }
        let tray = LetterMultiset::from_letters(tray)?;
        Ok(AnagramQuery::new(slots, tray, wildcards))
    }
}

/// The in-memory shared dictionary for one [`Locale`].
///
/// Word forms are stored once, sorted and deduplicated, in an `fst` set — which
/// serves membership, ordered enumeration, and edit-distance suggestions from a
/// single compact structure (the reason `fst` was chosen).
pub struct Dictionary {
    locale: Locale,
    set: Set<Vec<u8>>,
    word_count: usize,
}

impl Dictionary {
    /// Load the dictionary for `locale` from its vendored word list.
    ///
    /// Each source line is trimmed and case-folded to lowercase; blanks are
    /// skipped and duplicates collapse. The result is built into an `fst` set in
    /// ascending byte order.
    pub fn load(locale: Locale) -> Result<Self, WordError> {
        // BTreeSet gives us sorted, unique, lowercase keys — exactly the order an
        // `fst` set must be built in.
        let mut sorted: BTreeSet<String> = BTreeSet::new();
        for line in locale.source().lines() {
            let word = line.trim();
            if word.is_empty() {
                continue;
            }
            sorted.insert(word.to_ascii_lowercase());
        }

        let word_count = sorted.len();
        let mut builder = SetBuilder::memory();
        for word in &sorted {
            builder
                .insert(word)
                .map_err(|e| WordError::DictionaryBuild(e.to_string()))?;
        }
        let bytes = builder
            .into_inner()
            .map_err(|e| WordError::DictionaryBuild(e.to_string()))?;
        let set = Set::new(bytes).map_err(|e| WordError::DictionaryBuild(e.to_string()))?;

        Ok(Dictionary {
            locale,
            set,
            word_count,
        })
    }

    /// The process-wide shared dictionary for `locale`, built once on first use.
    pub fn shared(locale: Locale) -> &'static Dictionary {
        match locale {
            Locale::EnUs => &EN_US_DICTIONARY,
        }
    }

    /// The locale this dictionary serves.
    pub fn locale(&self) -> Locale {
        self.locale
    }

    /// The number of distinct word forms in the dictionary.
    pub fn len(&self) -> usize {
        self.word_count
    }

    /// Whether the dictionary is empty.
    pub fn is_empty(&self) -> bool {
        self.word_count == 0
    }

    /// Spell-check: is `word` in the dictionary (case-insensitively)?
    pub fn contains(&self, word: &str) -> bool {
        self.set.contains(word.to_ascii_lowercase())
    }

    /// Enumerate every dictionary word that the regular expression `pattern`
    /// matches *in full*.
    ///
    /// The pattern is anchored to the whole word, so `"cat"` matches only `cat`,
    /// not `cats` or `scatter`. Results are returned in ascending lexicographic
    /// order. A malformed pattern yields [`WordError::InvalidRegex`].
    pub fn matching_regex(&self, pattern: &str) -> Result<Vec<String>, WordError> {
        let anchored = format!("^(?:{pattern})$");
        let regex = Regex::new(&anchored).map_err(|e| WordError::InvalidRegex(e.to_string()))?;

        let mut matches = Vec::new();
        let mut stream = self.set.stream();
        while let Some(key) = stream.next() {
            if let Ok(word) = std::str::from_utf8(key)
                && regex.is_match(word)
            {
                matches.push(word.to_string());
            }
        }
        Ok(matches)
    }

    /// Solve the anagram `query`: every dictionary word whose length matches the
    /// template, whose fixed positions agree with their given letters, and whose
    /// blank positions can be drawn from the tray (with wildcards covering any
    /// shortfall). Results are returned in ascending lexicographic order.
    pub fn anagrams(&self, query: &AnagramQuery) -> Vec<String> {
        let mut matches = Vec::new();
        let mut stream = self.set.stream();
        while let Some(key) = stream.next() {
            if let Ok(word) = std::str::from_utf8(key)
                && anagram_matches(word, query)
            {
                matches.push(word.to_string());
            }
        }
        matches
    }

    /// Suggest dictionary words within `max_edits` Levenshtein edits of `word`
    /// (case-folded), in ascending lexicographic order.
    ///
    /// An empty query yields no suggestions. A `max_edits` so large that the
    /// automaton cannot be built yields [`WordError::SuggestionTooBroad`].
    pub fn suggestions(&self, word: &str, max_edits: u32) -> Result<Vec<String>, WordError> {
        let query = word.to_ascii_lowercase();
        if query.is_empty() {
            return Ok(Vec::new());
        }
        let lev = Levenshtein::new(&query, max_edits)
            .map_err(|e| WordError::SuggestionTooBroad(e.to_string()))?;

        let mut matches = Vec::new();
        let mut stream = self.set.search(&lev).into_stream();
        while let Some(key) = stream.next() {
            if let Ok(word) = std::str::from_utf8(key) {
                matches.push(word.to_string());
            }
        }
        Ok(matches)
    }
}

/// The lazily-built process-wide US-English dictionary.
static EN_US_DICTIONARY: LazyLock<Dictionary> =
    LazyLock::new(|| Dictionary::load(Locale::EnUs).expect("vendored en-US dictionary must load"));

/// Map an ASCII letter to its `0..26` index, or `None` if it is not `a`–`z`.
fn letter_index(ch: char) -> Option<usize> {
    if ch.is_ascii_lowercase() {
        Some(ch as usize - 'a' as usize)
    } else {
        None
    }
}

/// Decide whether `word` satisfies the anagram `query`.
///
/// The word is ASCII (the vendored list is); a word containing any character
/// that is not an `a`–`z` tile can never be produced at a blank position, so it
/// is rejected there.
fn anagram_matches(word: &str, query: &AnagramQuery) -> bool {
    // The template length fixes the word length. The vendored words are ASCII,
    // so a byte length equals a character count.
    if word.len() != query.template.len() {
        return false;
    }

    // Tally the letters the blanks demand; reject on any fixed-letter mismatch or
    // non-letter at a blank.
    let mut needed = [0u32; 26];
    for (slot, ch) in query.template.iter().zip(word.chars()) {
        match slot {
            Slot::Fixed(given) => {
                if ch != *given {
                    return false;
                }
            }
            Slot::Blank => match letter_index(ch) {
                Some(idx) => needed[idx] += 1,
                None => return false,
            },
        }
    }

    // The tray must cover the demand; wildcards make up any shortfall.
    let mut deficit: u32 = 0;
    for (idx, &want) in needed.iter().enumerate() {
        let have = query.tray.counts[idx];
        if want > have {
            deficit += want - have;
        }
    }
    deficit as usize <= query.wildcards
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dict() -> &'static Dictionary {
        Dictionary::shared(Locale::EnUs)
    }

    // --- dictionary loading / locale --------------------------------------

    #[test]
    fn shared_dictionary_is_en_us_and_substantial() {
        let d = dict();
        assert_eq!(d.locale(), Locale::EnUs);
        assert!(!d.is_empty());
        // The vendored SCOWL "medium" list is tens of thousands of words.
        assert!(
            d.len() > 50_000,
            "expected a substantial dictionary, got {}",
            d.len()
        );
    }

    // --- spell-check membership -------------------------------------------

    #[test]
    fn contains_common_words() {
        let d = dict();
        for w in ["hello", "world", "dictionary", "anagram", "word", "spell"] {
            assert!(d.contains(w), "expected {w:?} to be a word");
        }
    }

    #[test]
    fn membership_is_case_insensitive() {
        let d = dict();
        assert!(d.contains("Hello"));
        assert!(d.contains("HELLO"));
        assert!(d.contains("hElLo"));
    }

    #[test]
    fn rejects_non_words_and_empty() {
        let d = dict();
        for w in ["asdfgh", "qwertyzxcv", "zzzzz", ""] {
            assert!(!d.contains(w), "expected {w:?} not to be a word");
        }
    }

    // --- regex enumeration ------------------------------------------------

    #[test]
    fn regex_full_match_only() {
        let d = dict();
        let hits = d.matching_regex("cat").unwrap();
        // Anchored: only "cat" itself, never "cats" or "scatter".
        assert_eq!(hits, vec!["cat".to_string()]);
    }

    #[test]
    fn regex_character_class_three_letters() {
        let d = dict();
        let hits = d.matching_regex("c.t").unwrap();
        assert!(hits.contains(&"cat".to_string()));
        assert!(hits.contains(&"cot".to_string()));
        assert!(hits.contains(&"cut".to_string()));
        for w in &hits {
            assert_eq!(w.len(), 3, "{w:?} should be 3 letters");
            assert!(w.starts_with('c') && w.ends_with('t'));
        }
    }

    #[test]
    fn regex_results_are_sorted() {
        let d = dict();
        let hits = d.matching_regex("a..").unwrap();
        let mut sorted = hits.clone();
        sorted.sort();
        assert_eq!(hits, sorted, "enumeration must be lexicographically sorted");
        assert!(!hits.is_empty());
    }

    #[test]
    fn regex_invalid_pattern_errors() {
        let d = dict();
        let err = d.matching_regex("(unclosed").unwrap_err();
        assert!(matches!(err, WordError::InvalidRegex(_)));
    }

    // --- anagram solver: against the live dictionary ----------------------

    #[test]
    fn anagram_all_blanks_subset_of_tray() {
        let d = dict();
        let q = AnagramQuery::parse("...", "cat", 0).unwrap();
        let hits = d.anagrams(&q);
        assert!(hits.contains(&"cat".to_string()));
        assert!(hits.contains(&"act".to_string()));
        for w in &hits {
            assert_eq!(w.len(), 3);
            for ch in w.chars() {
                assert!("cat".contains(ch), "{w:?} uses a letter not in the tray");
            }
        }
    }

    #[test]
    fn anagram_fixed_letters_constrain_result() {
        let d = dict();
        // c _ t with only an 'a' to place: "cat" qualifies, "cot" does not.
        let q = AnagramQuery::parse("c.t", "a", 0).unwrap();
        let hits = d.anagrams(&q);
        assert!(hits.contains(&"cat".to_string()));
        assert!(!hits.contains(&"cot".to_string()));
    }

    #[test]
    fn anagram_wildcard_fills_any_blank() {
        let d = dict();
        // c _ t with an empty tray but one wildcard: the blank can be anything.
        let q = AnagramQuery::parse("c.t", "", 1).unwrap();
        let hits = d.anagrams(&q);
        assert!(hits.contains(&"cat".to_string()));
        assert!(hits.contains(&"cot".to_string()));
        assert!(hits.contains(&"cut".to_string()));
    }

    #[test]
    fn anagram_template_length_excludes_other_lengths() {
        let d = dict();
        let q = AnagramQuery::parse("....", "trace", 1).unwrap();
        let hits = d.anagrams(&q);
        for w in &hits {
            assert_eq!(w.len(), 4, "{w:?} should match the 4-slot template");
        }
    }

    #[test]
    fn anagram_insufficient_tray_yields_nothing() {
        let d = dict();
        // Three blanks but only two tiles and no wildcards: nothing can fill.
        let q = AnagramQuery::parse("...", "ab", 0).unwrap();
        assert!(d.anagrams(&q).is_empty());
    }

    // --- anagram solver: focused unit tests of the matcher ----------------

    #[test]
    fn anagram_matcher_respects_letter_multiplicity() {
        // "ee.." style demand: need two 'e's; a tray with one 'e' + one wildcard
        // suffices, but one 'e' alone does not.
        let template = vec![Slot::Blank, Slot::Blank];
        let one_e = AnagramQuery::new(template.clone(), LetterMultiset::from_letters("e").unwrap(), 0);
        assert!(!anagram_matches("ee", &one_e));

        let one_e_one_wild =
            AnagramQuery::new(template.clone(), LetterMultiset::from_letters("e").unwrap(), 1);
        assert!(anagram_matches("ee", &one_e_one_wild));

        let two_e = AnagramQuery::new(template, LetterMultiset::from_letters("ee").unwrap(), 0);
        assert!(anagram_matches("ee", &two_e));
    }

    #[test]
    fn anagram_matcher_rejects_non_letter_at_blank() {
        // A possessive form like "cat's" cannot be produced from letter tiles.
        let q = AnagramQuery::new(
            vec![Slot::Blank; 5],
            LetterMultiset::from_letters("acstx").unwrap(),
            5,
        );
        assert!(!anagram_matches("cat's", &q));
    }

    #[test]
    fn anagram_matcher_fixed_given_is_free() {
        // Fixed 'c' and 't' don't draw from the tray; only the middle blank does.
        let q = AnagramQuery::new(
            vec![Slot::Fixed('c'), Slot::Blank, Slot::Fixed('t')],
            LetterMultiset::from_letters("a").unwrap(),
            0,
        );
        assert!(anagram_matches("cat", &q));
        // Wrong fixed letter fails.
        assert!(!anagram_matches("bat", &q));
    }

    #[test]
    fn anagram_parse_rejects_bad_template_and_tray() {
        assert!(matches!(
            AnagramQuery::parse("c#t", "a", 0),
            Err(WordError::InvalidTemplate(_))
        ));
        assert!(matches!(
            AnagramQuery::parse("c.t", "a1", 0),
            Err(WordError::InvalidLetters(_))
        ));
    }

    // --- letter multiset --------------------------------------------------

    #[test]
    fn letter_multiset_counts_and_ignores_whitespace() {
        let ms = LetterMultiset::from_letters("a A b\tc ").unwrap();
        assert_eq!(ms.count('a'), 2);
        assert_eq!(ms.count('b'), 1);
        assert_eq!(ms.count('c'), 1);
        assert_eq!(ms.count('z'), 0);
        assert_eq!(ms.total(), 4);
    }

    // --- edit-distance suggestions ----------------------------------------

    #[test]
    fn suggestions_within_one_edit_include_target() {
        let d = dict();
        let hits = d.suggestions("helo", 1).unwrap();
        assert!(
            hits.contains(&"hello".to_string()),
            "expected 'hello' among {hits:?}"
        );
    }

    #[test]
    fn suggestions_distance_zero_is_exact() {
        let d = dict();
        let hits = d.suggestions("hello", 0).unwrap();
        assert_eq!(hits, vec!["hello".to_string()]);
    }

    #[test]
    fn suggestions_are_sorted() {
        let d = dict();
        let hits = d.suggestions("word", 1).unwrap();
        let mut sorted = hits.clone();
        sorted.sort();
        assert_eq!(hits, sorted);
        assert!(hits.contains(&"word".to_string()));
    }

    #[test]
    fn suggestions_empty_query_is_empty() {
        let d = dict();
        assert!(d.suggestions("", 2).unwrap().is_empty());
    }

    #[test]
    fn suggestions_is_case_insensitive() {
        let d = dict();
        let hits = d.suggestions("HELLO", 0).unwrap();
        assert_eq!(hits, vec!["hello".to_string()]);
    }
}
