if(EXISTS "/home/runner/work/m/m/build-test/src/libraries/arefc_ptr/test/test_arc_ptr[1]_tests.cmake")
  include("/home/runner/work/m/m/build-test/src/libraries/arefc_ptr/test/test_arc_ptr[1]_tests.cmake")
else()
  add_test(test_arc_ptr_NOT_BUILT test_arc_ptr_NOT_BUILT)
endif()
