name: Build Clang Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install build dependencies
        run: sudo apt install -y ninja-build

      - name: Clone LLVM
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          repository: llvm/llvm-project
          path: llvm
      - name: Setting Clang
        working-directory: llvm
        run: |
          cmake -DLLVM_ENABLE_PROJECTS="clang" \
          -DCMAKE_BUILD_TYPE="Release" \
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/clang" \
          -DLLVM_PARALLEL_LINK_JOBS=2 \
          -S llvm -B build -G Ninja
      - name: Building Clang
        working-directory: llvm
        run: cmake --build build
      - name: Install Clang
        working-directory: llvm/build
        run: ninja install
      - name: Upload Clang binary
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: clang-binary
          path: ${{ github.workspace }}/clang

